import Head from 'next/head'
import Layout from '../components/Layout'
import Home from '../components/Home'
import Projects from '../components/Projects'
import About from '../components/About'
import Contact from '../components/Contact'

export default function LandingPage() {
  return (
    <div>
      <Head>
        <title>Portfolio | Nathan Brodin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Home />
        <Projects />
        <About />
        <Contact />
      </Layout>
    </div>
  )
}
